---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요. 
---
= 모든 클라우드 공급자의 Cloud Volumes ONTAP 에 대한 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하세요.

다음 제한 사항은 AWS, Azure, Google Cloud 등 모든 클라우드 공급자의 Cloud Volumes ONTAP 에 적용됩니다.



== 지원되지 않는 ONTAP 기능

다음 기능은 Cloud Volumes ONTAP 에서 지원되지 않습니다.

* 집계 수준 인라인 중복 제거
* 집계 수준 백그라운드 중복 제거
* 디스크 유지관리 센터
* 디스크 정리
* FabricPool 미러링
* 파이버 채널(FC)
* 플래시 풀
* 무한한 볼륨
* 인터페이스 그룹
* 노드 내 LIF 장애 조치
* MetroCluster
* 다중 관리자 검증
+
Cloud Volumes ONTAP 에서 다중 관리자 검증을 활성화하면 지원되지 않는 구성이 발생합니다.

* RAID4, RAID-DP, RAID-TEC (RAID0 지원)
* 서비스 프로세서
* SnapLock Compliance 및 엔터프라이즈 모드(Cloud WORM만 지원됨)
* SnapMirror 동기식
* VLAN
* SMB 지속적 가용성(CA)
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["지속적으로 이용 가능한 SMB 주식"^] 중단 없는 운영에는 지원되지 않습니다.





== 최대 동시 복제 작업

Cloud Volumes ONTAP 의 동시 SnapMirror 또는 SnapVault 전송 최대 수는 인스턴스 유형이나 머신 유형에 관계없이 노드당 100개입니다.



== 클라우드 공급자 스냅샷은 백업 및 복구 계획에 사용할 수 없습니다.

Cloud Volumes ONTAP 데이터의 백업 및 복구 계획의 일부로 클라우드 제공업체의 스냅샷을 사용해서는 안 됩니다.  Cloud Volumes ONTAP 에 호스팅된 데이터를 백업하고 복원하려면 항상 ONTAP 스냅샷 복사본이나 타사 백업 솔루션을 사용해야 합니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["BlueXP backup and recovery 사용하여 ONTAP 데이터를 백업하고 복원하는 방법을 알아보세요."^] .


NOTE: WAFL 파일 시스템의 ONTAP 일관성 지점은 데이터 일관성을 결정합니다.  ONTAP 만이 WAFL 파일 시스템을 중지하여 충돌 발생 시에도 일관된 백업을 수행할 수 있습니다.



== Cloud Volumes ONTAP 예약된 VM 인스턴스와 주문형 VM 인스턴스만 지원합니다.

Cloud Volumes ONTAP 클라우드 공급자의 예약된 VM 인스턴스나 주문형 VM 인스턴스에서 실행될 수 있습니다.  다른 유형의 VM 인스턴스는 지원되지 않습니다.



== 자동 애플리케이션 리소스 관리 솔루션을 사용해서는 안 됩니다.

자동 애플리케이션 리소스 관리 솔루션은 Cloud Volumes ONTAP 시스템을 관리해서는 안 됩니다.  그렇게 하면 지원되지 않는 구성이 변경될 수 있습니다.  예를 들어, 솔루션은 Cloud Volumes ONTAP 지원되지 않는 VM 인스턴스 유형으로 변경할 수 있습니다.



== 소프트웨어 업데이트는 BlueXP 에서 완료해야 합니다.

Cloud Volumes ONTAP 업그레이드는 BlueXP 에서 완료해야 합니다.  System Manager나 CLI를 사용하여 Cloud Volumes ONTAP 업그레이드해서는 안 됩니다.  그렇게 하면 시스템 안정성에 영향을 미칠 수 있습니다.



== Cloud Volumes ONTAP 배포는 클라우드 공급자의 콘솔에서 수정되어서는 안 됩니다.

클라우드 공급자의 콘솔에서 Cloud Volumes ONTAP 구성을 변경하면 지원되지 않는 구성이 발생합니다.  BlueXP 생성하고 관리하는 Cloud Volumes ONTAP 리소스에 대한 변경 사항은 시스템 안정성과 BlueXP의 시스템 관리 능력에 영향을 미칠 수 있습니다.


NOTE: 초기 배포 후 Cloud Volumes ONTAP 리소스에 사용되는 Azure 구독 이름을 수정할 수 있습니다.



== 디스크와 집계는 BlueXP 에서 관리해야 합니다.

모든 디스크와 집계는 BlueXP 에서 직접 생성하고 삭제해야 합니다.  다른 관리 도구에서는 이러한 작업을 수행해서는 안 됩니다.  그렇게 하면 시스템 안정성에 영향을 미치고, 나중에 디스크를 추가하는 기능을 방해할 수 있으며, 잠재적으로 중복된 클라우드 공급자 수수료가 발생할 수 있습니다.



== SnapManager 라이선스 제한

Cloud Volumes ONTAP 에서는 서버당 SnapManager 라이선스가 지원됩니다.  스토리지 시스템별( SnapManager 제품군) 라이선스는 지원되지 않습니다.



== 타사 에이전트 및 확장 프로그램의 제한 사항

타사 에이전트와 VM 확장 프로그램은 Cloud Volumes ONTAP 가상 머신 인스턴스에서 지원되지 않습니다.
