---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP 안정적인 운영을 제공하기 위해 AWS에서 스토리지 구성에 제한이 있습니다.  최상의 성능을 얻으려면 시스템을 최대값으로 구성하지 마세요. 
---
= AWS의 Cloud Volumes ONTAP 대한 스토리지 한도
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 안정적인 운영을 제공하기 위해 스토리지 구성에 제한이 있습니다.  최상의 성능을 얻으려면 시스템을 최대값으로 구성하지 마세요.



== 라이선스별 최대 시스템 용량

최대 시스템 용량에는 디스크 기반 스토리지와 데이터 계층화에 사용되는 개체 스토리지가 포함됩니다.

NetApp 시스템 용량 제한을 초과하는 것을 지원하지 않습니다. 라이센스된 용량 한도에 도달하면 BlueXP 조치 필요 메시지가 표시되고 더 이상 디스크를 추가할 수 없습니다.

일부 구성의 경우 디스크 제한으로 인해 디스크만 사용하여 용량 제한에 도달할 수 없습니다.  이러한 경우에는 다음을 통해 용량 제한에 도달할 수 있습니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 개체 스토리지로 계층화"^] .  자세한 내용은 아래의 용량 및 디스크 제한을 참조하세요.

.용량 기반 라이선스에 대한 용량 제한
용량 기반 라이선싱을 통해 각 Cloud Volumes ONTAP 시스템은 개체 스토리지에 대한 계층화를 지원합니다. 전체 계층형 용량은 클라우드 제공자의 버킷 한도까지 확장될 수 있습니다. 라이센스에는 용량 제한이 부과되지 않지만 다음을 따라야 합니다. https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool 모범 사례"^] 계층화를 구성하고 관리할 때 최적의 성능, 안정성 및 비용 효율성을 보장합니다. 를 참조하세요  https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWS 문서"^] 자세한 내용은.

다른 라이센스 유형에 대한 용량 제한::


[cols="25,75"]
|===
| 특허 | 최대 시스템 용량(디스크 + 개체 스토리지) 


| 프리미엄 | 500기가바이트 


| PAYGO 탐색 | 2 TiB(Explore에서는 데이터 계층화가 지원되지 않음) 


| PAYGO 표준 | 10티비 


| 페이고 프리미엄 | 368티비 


| 노드 기반 라이센스 | 2 PiB(여러 라이선스 필요) 
|===
.HA의 경우, 라이선스 용량 제한은 노드당인가요, 아니면 전체 HA 쌍에 대한 것인가요?
용량 제한은 HA 쌍 전체에 적용됩니다. 노드당이 아닙니다. 예를 들어, 프리미엄 라이선스는 두 노드에서 최대 368TiB를 허용합니다.

.AWS의 HA 시스템의 경우 미러링된 데이터가 용량 제한에 포함됩니까?
아니, 그렇지 않아요. AWS HA 쌍의 데이터는 장애 발생 시에도 데이터를 사용할 수 있도록 노드 간에 동기적으로 미러링됩니다.  예를 들어, 노드 A에서 8TiB 디스크를 구매하는 경우 BlueXP 미러링된 데이터에 사용되는 노드 B에도 8TiB 디스크를 할당합니다.  16TiB의 용량이 프로비저닝되었지만, 라이선스 한도에는 8TiB만 포함됩니다.



== 집계 한도

Cloud Volumes ONTAP EBS 볼륨을 디스크로 사용하고 이를 _집계_로 그룹화합니다.  집계는 볼륨에 대한 저장소를 제공합니다.

[cols="2*"]
|===
| 매개변수 | 한계 


| 최대 집계 수 | 단일 노드: 디스크 제한과 동일 HA 쌍: 노드당 18개 ^1^ 


| 최대 집계 크기 ^2^  a| 
* 96TiB의 원시 용량
* Elastic Volumes를 사용한 128TiB의 원시 용량 ^3^




| 집계당 디스크 ^4^  a| 
* 1-6
* 탄력적 볼륨이 있는 1-8 ^3^




| 집계당 RAID 그룹의 최대 수 | 1 
|===
참고사항:

. HA 쌍의 두 노드 모두에 18개의 집계를 만들 수 없습니다. 그렇게 하면 데이터 디스크 한도를 초과하게 됩니다.
. 최대 집계 크기는 디스크에 따라 달라지며 데이터 계층화에 사용하는 개체 스토리지는 포함되지 않습니다.
. Amazon EBS Elastic Volumes 기능을 지원하는 구성이 있는 경우 집계에는 최대 8개의 디스크가 포함될 수 있으며, 이는 최대 128TiB의 용량을 제공합니다. 기본적으로 Cloud Volumes ONTAP 9.11.0 이상 시스템에서는 gp3 또는 io1 디스크를 사용할 때 Amazon EBS Elastic Volumes가 활성화됩니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Elastic Volumes 지원에 대해 자세히 알아보세요"^]
. 집계된 모든 디스크의 크기는 동일해야 합니다.




== EC2 인스턴스별 디스크 및 계층화 제한

용량 한도는 사용하는 EC2 인스턴스 유형 패밀리와 단일 노드 시스템을 사용하는지 HA 쌍을 사용하는지에 따라 다릅니다.

다음 참고사항에서는 아래 표에 나오는 숫자에 대한 세부 정보를 제공합니다.

* 디스크 제한은 사용자 데이터가 포함된 디스크에만 적용됩니다.
+
이 제한에는 부팅 디스크와 루트 디스크는 포함되지 않습니다.

* 디스크만 사용할 경우와 디스크와 콜드 데이터 계층화를 함께 사용하여 개체 스토리지를 사용할 경우의 최대 시스템 용량이 나열되어 있습니다.
* Cloud Volumes ONTAP EBS 볼륨을 디스크로 사용하며, 최대 디스크 크기는 16TiB입니다.




=== 용량 기반 라이선싱의 다양한 배포 모드에 대한 제한

다음 디스크 제한은 용량 기반 라이선스 패키지를 사용하는 Cloud Volumes ONTAP 시스템에 적용됩니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP 라이선싱 옵션에 대해 알아보세요"^]


NOTE: 단일 노드 및 HA 구성에 대한 최대 시스템 용량 및 데이터 계층화 용량 제한은 다음을 참조하세요.<<cap-license-aws>> .



==== 단일 노드

[cols="18,18,32,width=100%,options="]
|===


| 사례 | 노드당 최대 디스크 수 | 디스크만 포함한 최대 시스템 용량 


| c5, m5 및 r5 인스턴스 | 21 | 336티비 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19 ^1^ | 304티비 
|===
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수가 더 적습니다.




==== HA 쌍

[cols="18,18,32,width=100%,options="]
|===


| 사례 | 노드당 최대 디스크 수 | 디스크만 포함한 최대 시스템 용량 


| c5, m5 및 r5 인스턴스 | 18 | 288티비 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16^1^ | 256티비 
|===
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수가 더 적습니다.




=== 노드 기반 라이선싱의 다양한 배포 모드에 대한 제한 사항

다음 디스크 제한은 노드 기반 라이선싱을 사용하는 Cloud Volumes ONTAP 시스템에 적용됩니다. 노드 기반 라이선싱은 노드별로 Cloud Volumes ONTAP 대한 라이선스를 부여할 수 있는 이전 세대 라이선스 모델입니다. 기존 고객에게는 노드 기반 라이선싱이 계속 제공됩니다.

Cloud Volumes ONTAP BYOL 단일 노드 또는 HA 쌍 시스템에 대해 여러 개의 노드 기반 라이선스를 구매하여 최대 테스트 및 지원되는 시스템 용량 한도인 2PiB까지 368TiB 이상의 용량을 할당할 수 있습니다. 디스크 제한으로 인해 디스크만 사용하여 용량 제한에 도달하지 못할 수도 있습니다. 디스크 한도를 초과할 수 있습니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 개체 스토리지로 계층화"^] . https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Cloud Volumes ONTAP 에 추가 시스템 라이선스를 추가하는 방법을 알아보세요."^] . Cloud Volumes ONTAP 테스트 및 지원되는 최대 시스템 용량인 2PiB까지 지원하지만, 2PiB 제한을 초과하면 지원되지 않는 시스템 구성이 발생합니다.

AWS Secret Cloud 및 Top Secret Cloud 리전에서는 Cloud Volumes ONTAP 9.12.1부터 여러 노드 기반 라이선스 구매를 지원합니다.



==== PAYGO Premium을 사용한 단일 노드

[cols="18,18,32,32"]
|===
| 사례 | 노드당 최대 디스크 수 | 디스크만 포함한 최대 시스템 용량 | 디스크 및 데이터 계층화를 통한 최대 시스템 용량 


| c5, m5 및 r5 인스턴스 | 21 ^1^ | 336티비 | 368티비 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19^2^ | 304티비 | 368티비 
|===
. Cloud Volumes ONTAP 의 _새로운_ 배포에 대한 데이터 디스크 제한은 21개입니다.  9.7 이전 버전으로 만든 시스템을 업그레이드하면 해당 시스템은 계속 22개의 디스크를 지원합니다.  9.8 릴리스부터 핵심 디스크가 추가되어 이러한 인스턴스 유형을 사용하는 새 시스템에서는 지원되는 데이터 디스크가 하나 줄었습니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수가 더 적습니다.




==== BYOL을 사용한 단일 노드

[cols="18,18,16,16,16,16"]
|===
| 사례 | 노드당 최대 디스크 수 2+| 하나의 라이선스로 최대 시스템 용량을 확보하세요 2+| 여러 라이선스를 사용한 최대 시스템 용량 


2+|  | *디스크만* | *디스크 + 데이터 계층화* | *디스크만* | *디스크 + 데이터 계층화* 


| c5, m5 및 r5 인스턴스 | 21 ^1^ | 336티비 | 368티비 | 336티비 | 2파이비 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 19^2^ | 304티비 | 368티비 | 304티비 | 2파이비 
|===
. Cloud Volumes ONTAP 의 _새로운_ 배포에 대한 데이터 디스크 제한은 21개입니다.  9.7 이전 버전으로 만든 시스템을 업그레이드하면 해당 시스템은 계속 22개의 디스크를 지원합니다.  9.8 릴리스부터 핵심 디스크가 추가되어 이러한 인스턴스 유형을 사용하는 새 시스템에서는 지원되는 데이터 디스크가 하나 줄었습니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수가 더 적습니다.




==== PAYGO Premium과 HA 페어링

[cols="18,18,32,32"]
|===
| 사례 | 노드당 최대 디스크 수 | 디스크만 포함한 최대 시스템 용량 | 디스크 및 데이터 계층화를 통한 최대 시스템 용량 


| c5, m5 및 r5 인스턴스 | 18^1^ | 288티비 | 368티비 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16^2^ | 256티비 | 368티비 
|===
. Cloud Volumes ONTAP 의 _새로운_ 배포에 대한 데이터 디스크 제한은 18개입니다.  9.7 이전 버전으로 만든 시스템을 업그레이드하면 해당 시스템은 계속 19개의 디스크를 지원합니다.  9.8 릴리스부터 핵심 디스크가 추가되어 이러한 인스턴스 유형을 사용하는 새 시스템에서는 지원되는 데이터 디스크가 하나 줄었습니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수가 더 적습니다.




==== BYOL과 HA 페어링

[cols="18,18,16,16,16,16"]
|===
| 사례 | 노드당 최대 디스크 수 2+| 하나의 라이선스로 최대 시스템 용량을 확보하세요 2+| 여러 라이선스를 사용한 최대 시스템 용량 


2+|  | *디스크만* | *디스크 + 데이터 계층화* | *디스크만* | *디스크 + 데이터 계층화* 


| c5, m5 및 r5 인스턴스 | 18^1^ | 288티비 | 368티비 | 288티비 | 2파이비 


 a| 
* m5dn.24xlarge
* m6id.32xlarge

| 16^2^ | 256티비 | 368티비 | 256티비 | 2파이비 
|===
. Cloud Volumes ONTAP 의 _새로운_ 배포에 대한 데이터 디스크 제한은 18개입니다.  9.7 이전 버전으로 만든 시스템을 업그레이드하면 해당 시스템은 계속 19개의 디스크를 지원합니다.  9.8 릴리스부터 핵심 디스크가 추가되어 이러한 인스턴스 유형을 사용하는 새 시스템에서는 지원되는 데이터 디스크가 하나 줄었습니다.
. 이 인스턴스 유형은 다른 인스턴스 유형보다 로컬 NVMe 디스크가 더 많으므로 지원되는 데이터 디스크 수가 더 적습니다.




== 스토리지 VM 제한

일부 구성을 사용하면 Cloud Volumes ONTAP 대한 추가 스토리지 VM(SVM)을 생성할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["추가 스토리지 VM을 만드는 방법을 알아보세요"^] .

[cols="40,60"]
|===
| 라이센스 유형 | 스토리지 VM 제한 


| *프리미엄*  a| 
총 24개의 스토리지 VM ^1,2^



| *용량 기반 PAYGO 또는 BYOL* ^3^  a| 
총 24개의 스토리지 VM ^1,2^



| *노드 기반 PAYGO*  a| 
* 데이터 제공을 위한 1개의 스토리지 VM
* 재해 복구를 위한 1개의 스토리지 VM




| *노드 기반 BYOL* ^4^  a| 
* 총 24개의 스토리지 VM ^1,2^


|===
. 사용하는 EC2 인스턴스 유형에 따라 한도가 더 낮아질 수 있습니다.  인스턴스당 제한 사항은 아래 섹션에 나와 있습니다.
. 이러한 24개의 스토리지 VM은 데이터를 제공하거나 재해 복구(DR)를 위해 구성될 수 있습니다.
. 용량 기반 라이선싱의 경우 추가 스토리지 VM에 대한 별도 라이선싱 비용은 없지만 스토리지 VM당 최소 4TiB 용량 요금이 부과됩니다.  예를 들어, 두 개의 스토리지 VM을 생성하고 각각에 2TiB의 프로비저닝 용량이 있는 경우 총 8TiB의 요금이 청구됩니다.
. 노드 기반 BYOL의 경우, 기본적으로 Cloud Volumes ONTAP 과 함께 제공되는 첫 번째 스토리지 VM 외에 추가 _데이터 제공_ 스토리지 VM이 하나 더 필요할 때마다 애드온 라이선스가 필요합니다. 스토리지 VM 추가 라이선스를 받으려면 계정 팀에 문의하세요.
+
재해 복구(DR)를 위해 구성하는 스토리지 VM에는 추가 라이선스가 필요하지 않습니다(무료임). 하지만 스토리지 VM 한도에는 포함됩니다.  예를 들어, 데이터 제공 스토리지 VM이 12개이고 재해 복구를 위해 구성된 스토리지 VM이 12개 있는 경우 한도에 도달하여 추가 스토리지 VM을 만들 수 없습니다.





=== EC2 인스턴스 유형별 스토리지 VM 제한

추가 스토리지 VM을 생성할 때 포트 e0a에 개인 IP 주소를 할당해야 합니다.  아래 표는 Cloud Volumes ONTAP 배포된 후 인터페이스당 최대 개인 IP 수와 포트 e0a에서 사용 가능한 IP 주소 수를 나타냅니다.  사용 가능한 IP 주소의 수는 해당 구성에 대한 최대 스토리지 VM 수에 직접적인 영향을 미칩니다.

아래 나열된 인스턴스는 c5, m5, r5 인스턴스 제품군을 위한 것입니다.

[cols="6*"]
|===
| 구성 | 인스턴스 유형 | 인터페이스당 최대 개인 IP | 배포 후 남은 IP ^1^ | 관리 LIF가 없는 최대 스토리지 VM ^2,3^ | 관리 LIF가 있는 최대 스토리지 VM ^2,3^ 


.9+| *단일 노드* | *.xlarge | 15 | 9 | 10 | 5 


| *.2xlarge | 15 | 9 | 10 | 5 


| *.4xlarge | 30 | 24 | 24 | 12 


| *.8xlarge | 30 | 24 | 24 | 12 


| *.9xlarge | 30 | 24 | 24 | 12 


| *.12xlarge | 30 | 24 | 24 | 12 


| *.16xlarge | 50 | 44 | 24 | 12 


| *.18xlarge | 50 | 44 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *단일 AZ의 HA 쌍* | *.xlarge | 15 | 10 | 11 | 5 


| *.2xlarge | 15 | 10 | 11 | 5 


| *.4xlarge | 30 | 25 | 24 | 12 


| *.8xlarge | 30 | 25 | 24 | 12 


| *.9xlarge | 30 | 25 | 24 | 12 


| *.12xlarge | 30 | 25 | 24 | 12 


| *.16xlarge | 50 | 45 | 24 | 12 


| *.18xlarge | 50 | 45 | 24 | 12 


| *.24xlarge | 50 | 44 | 24 | 12 


.9+| *다중 AZ의 HA 쌍* | *.xlarge | 15 | 12 | 13 | 13 


| *.2xlarge | 15 | 12 | 13 | 13 


| *.4xlarge | 30 | 27 | 24 | 24 


| *.8xlarge | 30 | 27 | 24 | 24 


| *.9xlarge | 30 | 27 | 24 | 24 


| *.12xlarge | 30 | 27 | 24 | 24 


| *.16xlarge | 50 | 47 | 24 | 24 


| *.18xlarge | 50 | 47 | 24 | 24 


| *.24xlarge | 50 | 44 | 24 | 12 
|===
. 이 숫자는 Cloud Volumes ONTAP 배포되고 설정된 후 포트 e0a에서 사용 가능한 개인 IP 주소가 몇 개 남았는지 나타냅니다.  예를 들어, *.2xlarge 시스템은 네트워크 인터페이스당 최대 15개의 IP 주소를 지원합니다.  HA 쌍이 단일 AZ에 배포되는 경우 5개의 개인 IP 주소가 포트 e0a에 할당됩니다.  결과적으로 *.2xlarge 인스턴스 유형을 사용하는 HA 쌍에는 추가 스토리지 VM을 위해 10개의 개인 IP 주소가 남습니다.
. 이 열에 나열된 숫자에는 BlueXP 기본적으로 생성하는 초기 스토리지 VM이 포함되어 있습니다.  예를 들어, 이 열에 24가 나열되어 있다면 총 24개까지 추가 스토리지 VM을 만들 수 있다는 의미입니다.
. 스토리지 VM에 대한 관리 LIF는 선택 사항입니다.  관리 LIF는 SnapCenter 와 같은 관리 도구에 대한 연결을 제공합니다.
+
개인 IP 주소가 필요하므로 생성할 수 있는 추가 스토리지 VM 수가 제한됩니다.  유일한 예외는 여러 AZ에 있는 HA 쌍입니다.  이 경우 관리 LIF의 IP 주소는 _유동_ IP 주소이므로 _개인_ IP 제한에 포함되지 않습니다.





== 파일 및 볼륨 제한

[cols="22,22,56"]
|===
| 논리적 저장소 | 매개변수 | 한계 


.2+| *파일* | 최대 크기 ^2^ | 128TB 


| 볼륨당 최대 | 볼륨 크기에 따라 최대 20억까지 


| * FlexClone 볼륨* | 계층적 복제 깊이 ^1^ | 499 


.3+| * FlexVol 볼륨* | 노드당 최대 | 500 


| 최소 크기 | 20MB 


| 최대 크기 ^3^ | 300티비 


| *큐트리스* | FlexVol volume 당 최대값 | 4,995 


| *스냅샷 사본* | FlexVol volume 당 최대값 | 1,023 
|===
. 계층적 복제 깊이는 단일 FlexVol volume 에서 생성될 수 있는 FlexClone 볼륨의 중첩 계층의 최대 깊이입니다.
. ONTAP 9.12.1P2부터 제한은 128TB입니다.  ONTAP 9.11.1 및 이전 버전에서는 제한이 16TB입니다.
. 다음 도구와 최소 버전을 사용하면 최대 300TiB 크기의 FlexVol volume 생성할 수 있습니다.
+
** Cloud Volumes ONTAP 9.12.1 P2 및 9.13.0 P2부터 시작하는 시스템 관리자 및 ONTAP CLI
** Cloud Volumes ONTAP 9.13.1부터 BlueXP 시작






== iSCSI 스토리지 제한

[cols="3*"]
|===
| iSCSI 스토리지 | 매개변수 | 한계 


.4+| *LUN* | 노드당 최대 | 1,024 


| LUN 맵의 최대 수 | 1,024 


| 최대 크기 | 16티비 


| 볼륨당 최대 | 512 


| *아이그룹* | 노드당 최대 | 256 


.2+| *개시자* | 노드당 최대 | 512 


| igroup당 최대값 | 128 


| *iSCSI 세션* | 노드당 최대 | 1,024 


.2+| *LIFs* | 포트당 최대 | 32 


| 포트셋당 최대값 | 32 


| *포트셋* | 노드당 최대 | 256 
|===