---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.16.1에는 새로운 기능이 추가되었습니다. 
---
= Cloud Volumes ONTAP 9.16.1의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.16.1에는 새로운 기능이 추가되었습니다.

BlueXP 의 최신 버전에서는 추가 기능과 향상된 기능도 도입되었습니다.  를 참조하십시오 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP 릴리스 노트"^] 자세한 내용은.



== 9.16.1 P7(2025년 10월 9일)

이제 Azure 및 Google Cloud에서 Cloud Volumes ONTAP 에 9.16.1 P7 패치를 배포하고 업그레이드할 수 있습니다. 하지만 이 버전은 AWS에서는 배포 및 업그레이드할 수 없습니다. NetApp Console 기존 시스템을 이 패치 릴리스로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P7["P7 패치에서 수정된 버그 목록을 확인하세요"^] (NetApp 지원 사이트에 로그인이 필요합니다).



== 9.16.1 P6(2025년 10월 9일)

이제 Azure 및 Google Cloud에서 Cloud Volumes ONTAP 에 9.16.1 P6 패치를 배포하고 업그레이드할 수 있습니다. 하지만 이 버전은 AWS에서는 배포 및 업그레이드할 수 없습니다. NetApp Console 기존 시스템을 이 패치 릴리스로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P6["P6 패치에서 수정된 버그 목록을 확인하세요"^] (NetApp 지원 사이트에 로그인이 필요합니다).



== 9.16.1 P5(2025년 7월 28일)

이제 Azure 및 Google Cloud에서 Cloud Volumes ONTAP 에 9.16.1 P5 패치를 배포하고 업그레이드할 수 있습니다. 하지만 이 버전은 AWS에서는 배포 및 업그레이드할 수 없습니다. BlueXP 기존 시스템을 이 패치 릴리스로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P5["P5 패치에서 수정된 버그 목록을 확인하세요"^] (NetApp 지원 사이트에 로그인이 필요합니다).



== 9.16.1 P4(2025년 7월 8일)

이제 Azure 및 Google Cloud에서 Cloud Volumes ONTAP 에 9.16.1 P4 패치를 배포하고 업그레이드할 수 있습니다. 하지만 이 버전은 AWS에서는 배포 및 업그레이드할 수 없습니다. BlueXP 기존 시스템을 이 패치 릴리스로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P4["P4 패치에서 수정된 버그 목록을 확인하세요"^] (NetApp 지원 사이트에 로그인이 필요합니다).



== 9.16.1 P3(2025년 5월 29일)

이제 Azure 및 Google Cloud에서 Cloud Volumes ONTAP 에 9.16.1 P3 패치를 배포하고 업그레이드할 수 있습니다. 하지만 이 버전은 AWS에서는 배포 및 업그레이드할 수 없습니다. BlueXP 기존 시스템을 이 패치 릴리스로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P3["P3 패치에서 수정된 버그 목록을 확인하세요"^] (NetApp 지원 사이트에 로그인이 필요합니다).



== 9.16.1 P2(2025년 4월 17일)

이제 Azure 및 Google Cloud에서 Cloud Volumes ONTAP 에 9.16.1 P2 패치를 배포하고 업그레이드할 수 있습니다. 하지만 이 버전은 AWS에서는 배포 및 업그레이드할 수 없습니다. BlueXP 기존 시스템을 이 패치 릴리스로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P2["P2 패치에서 수정된 버그 목록을 확인하세요"^] (NetApp 지원 사이트에 로그인이 필요합니다).



== 9.16.1 P1(2025년 4월 17일)

이제 Azure 및 Google Cloud에서 Cloud Volumes ONTAP 에 9.16.1 P1 패치를 배포하고 업그레이드할 수 있습니다. 하지만 이 버전은 AWS에서는 배포 및 업그레이드할 수 없습니다. BlueXP 기존 시스템을 이 패치 릴리스로 업그레이드하라는 메시지를 표시합니다.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P1["P1 패치에서 수정된 버그 목록을 확인하세요"^] (NetApp 지원 사이트에 로그인이 필요합니다).



== 9.16.1 GA(2025년 3월 6일)

이제 Cloud Volumes ONTAP 9.16.1 일반 공급 릴리스를 사용하여 Azure와 Google Cloud에서 배포하고 업그레이드할 수 있습니다. 하지만 이 버전은 AWS에서는 배포 및 업그레이드할 수 없습니다.



== 업그레이드 노트

이 릴리스로 업그레이드하는 방법에 대한 자세한 내용을 알아보려면 이 노트를 읽어보세요.



=== 업그레이드 방법

Cloud Volumes ONTAP 업그레이드는 BlueXP 에서 완료해야 합니다.  System Manager나 CLI를 사용하여 Cloud Volumes ONTAP 업그레이드해서는 안 됩니다.  그렇게 하면 시스템 안정성에 영향을 미칠 수 있습니다.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXP 에서 알림을 받으면 업그레이드하는 방법을 알아보세요."^] .



=== 지원되는 업그레이드 경로

Azure 및 Google Cloud에서 9.15.1 릴리스에서 Cloud Volumes ONTAP 9.16.1 GA로 업그레이드할 수 있습니다. BlueXP 적격 Cloud Volumes ONTAP 시스템을 이 릴리스로 업그레이드하라는 메시지를 표시합니다.


NOTE: AWS의 경우 이 업그레이드에 대한 메시지가 표시되지 않습니다. AWS에서는 Cloud Volumes ONTAP 9.16.1 GA로의 업그레이드가 지원되지 않습니다.



=== 중단 시간

* 단일 노드 시스템을 업그레이드하면 최대 25분 동안 시스템이 오프라인 상태가 되며, 이때 I/O가 중단됩니다.
* HA 쌍을 업그레이드하는 것은 중단 없이 이루어지며 I/O도 중단되지 않습니다.  이러한 중단 없는 업그레이드 프로세스 동안 각 노드는 클라이언트에 I/O를 계속 제공하기 위해 동시에 업그레이드됩니다.

