---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s, aws outpost, outposts 
summary: 이러한 알려진 제한 사항은 Amazon Web Services의 Cloud Volumes ONTAP 에만 적용됩니다. 
---
= AWS의 Cloud Volumes ONTAP 에 대한 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음은 Amazon Web Services의 Cloud Volumes ONTAP 에만 적용되는 알려진 제한 사항입니다.  또한 검토해 보세요link:reference-limitations.html["모든 클라우드 공급자의 Cloud Volumes ONTAP 에 대한 제한 사항"] .



== AWS Outpost 제한 사항

AWS Outpost가 있는 경우 작업 환경 마법사에서 Outpost VPC를 선택하여 해당 Outpost에 Cloud Volumes ONTAP 배포할 수 있습니다.  경험은 AWS에 있는 다른 VPC와 동일합니다.  먼저 AWS Outpost에 커넥터를 배포해야 합니다.

지적해야 할 몇 가지 제한 사항이 있습니다.

* 현재 단일 노드 Cloud Volumes ONTAP 시스템만 지원됩니다.
* Cloud Volumes ONTAP 과 함께 사용할 수 있는 EC2 인스턴스는 Outpost에서 사용 가능한 인스턴스로 제한됩니다.
* 현재는 일반용 SSD(gp2)만 지원됩니다.




== 플래시 캐시 제한 사항

C5D 및 R5D 인스턴스 유형에는 로컬 NVMe 스토리지가 포함되어 있으며, Cloud Volumes ONTAP 이를 _Flash Cache_로 사용합니다.  다음 제한 사항을 참고하세요.

* Cloud Volumes ONTAP 9.12.0까지 Flash Cache 성능 향상을 활용하려면 모든 볼륨에서 압축을 비활성화해야 합니다.  Cloud Volumes ONTAP 9.12.1을 배포하거나 업그레이드하는 경우 압축을 비활성화할 필요가 없습니다.
+
BlueXP 에서 볼륨을 생성할 때 저장 효율성을 선택하지 않거나 볼륨을 생성한 다음 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["CLI를 사용하여 데이터 압축을 비활성화합니다."^] .

* Cloud Volumes ONTAP 에서는 재부팅 후 캐시 재가동이 지원되지 않습니다.




== Amazon CloudWatch에서 보고된 허위 경보

Cloud Volumes ONTAP 유휴 상태일 때 CPU를 해제하지 않으므로 https://aws.amazon.com/cloudwatch/["아마존 클라우드워치"^] EC2 인스턴스의 CPU 사용량이 100%이므로 높은 CPU 경고를 보고할 수 있습니다.  이 알람은 무시해도 됩니다.  ONTAP 통계 명령은 CPU의 실제 사용량을 표시합니다.



== Cloud Volumes ONTAP HA 쌍은 즉각적인 스토리지 반환을 지원하지 않습니다.

노드가 재부팅된 후에는 파트너가 저장소를 반환하기 전에 데이터를 동기화해야 합니다.  데이터를 재동기화하는 데 걸리는 시간은 노드가 다운된 동안 클라이언트가 작성한 데이터 양과 복구 시간 동안의 데이터 쓰기 속도에 따라 달라집니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha.html["AWS에서 실행되는 Cloud Volumes ONTAP HA 쌍에서 스토리지가 작동하는 방식을 알아보세요."^] .
